
trigger:
- master

jobs:
- job: "Build Gatsby Application using Node.JS"
  pool:
    vmImage: "ubuntu-latest"

  steps:
  - checkout: none

  - task: NodeTool@0
    inputs:
      versionSpec: "18.2.0"
    displayName: 'Install Node.js'

  - script: |
      node --version
    displayName: 'Verify Node.js installation'

  - script: |
      npm install -g gatsby-cli
    displayName: 'Install Gatsby CLI'

  - script: |
      gatsby --version
    displayName: 'Verify Gatsby Cli Version'





